Underwatch/Controllers/FavoritesListController.cs
using Contracts;
using Microsoft.AspNet.Identity;
using Models.FavoritesList;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Underwatch.Data;

namespace Underwatch.Controllers
{
    [Authorize]
    public class FavoritesListController : Controller
    {
        private readonly IFavoritesService _favoritesService;

        public FavoritesListController(IFavoritesService favoritesService)
        {
            _favoritesService = favoritesService;
        }

        // Get: FavoritesList/Index
        public ActionResult Index()
        {
            var model = _favoritesService.GetFavorites();

            return View(model);
        }

        // Get: FavoritesList/Create
        public ActionResult Create()
        {
            var viewModel = new CreateFavoritesListViewModel();

            _favoritesService.DropDownCreate(viewModel);

            return View(viewModel);
        }

        // Post: FavoritesList/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateFavoritesListViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _favoritesService.DropDownCreate(viewModel);

            if (_favoritesService.CreateFavorites(viewModel))
            {
                TempData["SaveResult"] = "Your Underwatch was created!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Something went wrong! The Underwatch couldn't be created.");

            return View(viewModel);
        }

        // Get: FavoritesList/Details/{id}
        public ActionResult Details(int id)
        {
            var model = _favoritesService.GetFavoriteById(id);

            return View(model);
        }

        // Get: FavoritesList/Edit/{id}
        public ActionResult Edit(int id)
        {
            var detail = _favoritesService.GetFavoriteById(id);
            var model = new FavoritesEdit
            {
                ListId = detail.ListId,
                NewsId = detail.NewsId,
                GameId = detail.GameId,
            };

            model.ListId = id;
            _favoritesService.DropDownEdit(model);

            return View(model);
        }

        // Post: Favorites/Edit/{id}
        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FavoritesEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.ListId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            model.ListId = id;
            _favoritesService.DropDownEdit(model);

            if (_favoritesService.UpdateFavorites(model))
            {
                TempData["SaveResult"] = "The Underwatch was updated!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The Underwatch could not be updated because something went Whoopsie-Doodle!");
            return View(model);
        }

        // Get: FavoritesList/Delete/{id}
        public ActionResult Delete(int id)
        {
            var model = _favoritesService.GetFavoriteById(id);

            return View(model);
        }

        // Post: FavoritesList/Delete/{id}
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFavorite(int id)
        {
            _favoritesService.DeleteFavorite(id);

            TempData["SaveResult"] = "An Underwatch was successfully deleted!";

            return RedirectToAction("Index");
        }
    }
}

Underwatch/Controllers/GameController.cs
using Contracts;
using Data;
using Microsoft.AspNet.Identity;
using Models;
using Models.Game;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Underwatch.Data;

namespace Underwatch.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly IGameService _gameService;

        public GameController(IGameService gameService)
        {
            _gameService = gameService;
        }

        // Get: Game/Index
        public ActionResult Index()
        {
            var model = _gameService.GetGames();

            return View(model);
        }

        // Get: Game/Create
        public ActionResult Create()
        {
            return View();
        }

        // Post: Game/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GameCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (_gameService.CreateGame(model))
            {
                TempData["SaveResult"] = "Your Game was created!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Something went wrong! The Game couldn't be created.");

            return View(model);
        }

        // Get: Game/Details/{id}
        public ActionResult Details(int id)
        {
            var model = _gameService.GetGameById(id);

            return View(model);
        }

        // Get: Game/Edit/{id}
        public ActionResult Edit(int id)
        {
            var detail = _gameService.GetGameById(id);
            var model =
                new GameEdit
                {
                    GameId = detail.GameId,
                    Title = detail.Title,
                    Genre = detail.Genre,
                    ReleaseDate = detail.ReleaseDate,
                    IsReleased = detail.IsReleased,
                    EarlyAccess = detail.EarlyAccess,
                    GameWebsite = detail.GameWebsite,
                    IsOwned = detail.IsOwned,
                };
            return View(model);
        }

        // Post: Game/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, GameEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.GameId != id)
            {
                ModelState.AddModelError("", "Id does not match");
                return View(model);
            }

            if (_gameService.UpdateGame(model))
            {
                TempData["SaveResult"] = "Your Game was updated!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your game could not be updated.");
            return View(model);
        }

        // Get: Game/Delete/{id}
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var model = _gameService.GetGameById(id);

            return View(model);
        }

        // Post: Game/Delete/{id}
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteGame(int id)
        {
            _gameService.DeleteGame(id);

            TempData["SaveResult"] = "Your Game was deleted!";

            return RedirectToAction("Index");
        }
    }
}

Underwatch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Underwatch</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="~/Content/StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body style="background-color: #27282E; padding-top: 0;">
    <div id="bootstrapOverride">
        <div class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid col-md-10">
                <div class="navbar-header font-weight-bolder" id="underWatchLogo">
                    @Html.ActionLink("Underwatch", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navBar">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="nav-item">@Html.ActionLink("About", "About", "Home")</li>
                        <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home")</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">@Html.ActionLink("Games", "Index", "Game")</li>
                            <li class="nav-item">@Html.ActionLink("News", "Index", "News")</li>
                            <li class="nav-item">@Html.ActionLink("Underwatch List", "Index", "FavoritesList")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer class="footerclass">
                <p>&copy; @DateTime.Now.Year - Jonathan Carey </p>
            </footer>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>